// 职业-专业-选科 数据库 ------------------------------------------------------
//
// 30 个职业类型,每个绑定:
//   - Holland 三字码(从 RIASEC 推断)
//   - Big Five 适配信号(高/低优势项)
//   - 教育部本科专业目录代码(部分)
//   - 3+1+2 模式选科要求(必选 + 推荐),依据《选考科目要求指引(通用版)2021》
//
// 这是 v0 数据,覆盖中学生最常关心的方向。生产前需要:
//   - 与教育部专业目录最新版同步
//   - 补充强基计划 / 综合评价的额外约束
//   - 各省 3+1+2 vs 3+3 的差异处理(目前只覆盖 3+1+2 通用情况)
// ----------------------------------------------------------------------------

import type { CareerType } from "./types";

export const CAREERS: CareerType[] = [
  // ─── 健康服务型 ───────────────────────────────────────
  {
    id: "med-clinical",
    zh: "临床医学",
    category: "健康服务型",
    hollandCode: "ISA",
    bigFiveFit: { C: "high", A: "high" },
    cognitiveFit: { Gc: "high", Gf: "high" },
    majors: [
      { name: "临床医学", code: "100201K" },
      { name: "口腔医学", code: "100301K" },
      { name: "麻醉学",   code: "100202TK" },
      { name: "儿科学",   code: "100207TK" },
    ],
    subjectsRequired: ["物理", "化学", "生物"],
    description: "诊断与治疗、医患沟通;长期培训(本+硕+博+规培,共 8–11 年)",
    fitNotes: "高尽责性 + 高宜人性 + 强晶体知识是基础;能耐受长周期、高负荷者更合适",
  },
  {
    id: "med-pharmacy",
    zh: "药学",
    category: "健康服务型",
    hollandCode: "ICR",
    bigFiveFit: { C: "high" },
    majors: [
      { name: "药学",       code: "100701" },
      { name: "中药学",     code: "100801" },
      { name: "临床药学",   code: "100703TK" },
    ],
    subjectsRequired: ["物理", "化学"],
    subjectsRecommended: ["生物"],
    description: "药品研发、临床药学服务;化学 + 生物双重基础",
    fitNotes: "对化学有持续兴趣 + 高组织性 + 细致(高 C facet 组织性)是关键",
  },
  {
    id: "med-nursing",
    zh: "护理学",
    category: "健康服务型",
    hollandCode: "SIC",
    bigFiveFit: { A: "high", C: "high" },
    majors: [
      { name: "护理学",       code: "101101" },
      { name: "助产学",       code: "101102T" },
    ],
    subjectsRequired: ["化学", "生物"],
    subjectsRecommended: ["物理"],
    description: "病患照护、康复支持;就业稳定、需求大",
    fitNotes: "高同情心 + 高责任感 + 能在高压下保持冷静",
  },

  // ─── 工程技术型 ───────────────────────────────────────
  {
    id: "eng-cs",
    zh: "计算机 / 软件工程",
    category: "工程技术型",
    hollandCode: "IRC",
    bigFiveFit: { O: "high", C: "high" },
    cognitiveFit: { Gf: "high" },
    majors: [
      { name: "计算机科学与技术", code: "080901" },
      { name: "软件工程",         code: "080902" },
      { name: "人工智能",         code: "080910T" },
      { name: "数据科学与大数据", code: "080910T" },
      { name: "网络空间安全",     code: "080911TK" },
    ],
    subjectsRequired: ["物理"],
    subjectsRecommended: ["化学"],
    description: "软件开发、算法、AI、数据;就业广、薪资高、强迭代",
    fitNotes: "高开放性 + 高流体推理 + 能独立思考长时间;需要持续自学",
  },
  {
    id: "eng-electrical",
    zh: "电子 / 电气工程",
    category: "工程技术型",
    hollandCode: "IRE",
    bigFiveFit: { C: "high" },
    cognitiveFit: { Gf: "high", Gv: "high" },
    majors: [
      { name: "电子信息工程",     code: "080701" },
      { name: "通信工程",         code: "080703" },
      { name: "电气工程及其自动化", code: "080601" },
      { name: "微电子科学与工程", code: "080704" },
    ],
    subjectsRequired: ["物理", "化学"],
    description: "硬件、电路、通信、芯片;制造业 + 互联网双轨需求",
    fitNotes: "强物理直觉 + 视觉空间能力(电路图)+ 耐心调试",
  },
  {
    id: "eng-mech",
    zh: "机械工程",
    category: "工程技术型",
    hollandCode: "RIC",
    bigFiveFit: { C: "high" },
    cognitiveFit: { Gv: "high" },
    majors: [
      { name: "机械工程",         code: "080201" },
      { name: "机械设计制造及其自动化", code: "080202" },
      { name: "车辆工程",         code: "080207" },
      { name: "机器人工程",       code: "080803T" },
    ],
    subjectsRequired: ["物理", "化学"],
    description: "机械设计、制造、自动化;传统工科,扎实需求",
    fitNotes: "高 R 实际型 + 强空间想象 + 高组织性",
  },
  {
    id: "eng-civil",
    zh: "土木 / 建筑",
    category: "工程技术型",
    hollandCode: "RIE",
    bigFiveFit: { C: "high" },
    cognitiveFit: { Gv: "high" },
    majors: [
      { name: "土木工程", code: "081001" },
      { name: "建筑学",   code: "082801" },
      { name: "城乡规划", code: "082802" },
    ],
    subjectsRequired: ["物理"],
    subjectsRecommended: ["化学"],
    description: "建筑设计、结构工程、施工管理;周期长、户外成分较多",
    fitNotes: "强空间感 + 现场协调能力(企业 E)+ 风险耐受",
  },

  // ─── 调研 / 科研型 ────────────────────────────────────
  {
    id: "sci-physics",
    zh: "物理 / 天文",
    category: "调研型",
    hollandCode: "IRA",
    bigFiveFit: { O: "high", C: "high" },
    cognitiveFit: { Gf: "high", Gv: "high" },
    majors: [
      { name: "物理学",   code: "070201" },
      { name: "应用物理", code: "070202" },
      { name: "天文学",   code: "070401" },
    ],
    subjectsRequired: ["物理"],
    subjectsRecommended: ["化学"],
    description: "基础研究为主;读研为常规出口;路线长",
    fitNotes: "极高开放性 + 流体推理 + 能在不确定中坚持长周期",
  },
  {
    id: "sci-chem",
    zh: "化学 / 材料",
    category: "调研型",
    hollandCode: "IRC",
    bigFiveFit: { C: "high" },
    majors: [
      { name: "化学",         code: "070301" },
      { name: "应用化学",     code: "070302" },
      { name: "材料科学与工程", code: "080401" },
    ],
    subjectsRequired: ["物理", "化学"],
    description: "实验科学;新材料、能源、医药为主流出口",
    fitNotes: "细致 + 耐心实验流程 + 高 C 组织性",
  },
  {
    id: "sci-bio",
    zh: "生物 / 生命科学",
    category: "调研型",
    hollandCode: "IRA",
    bigFiveFit: { O: "high", C: "high" },
    majors: [
      { name: "生物科学",       code: "071001" },
      { name: "生物技术",       code: "071002" },
      { name: "生物信息学",     code: "071003" },
      { name: "生物医学工程",   code: "082601" },
    ],
    subjectsRequired: ["化学", "生物"],
    subjectsRecommended: ["物理"],
    description: "生命系统研究;基础研究 + 医药 / 农业 / 环保产业",
    fitNotes: "强好奇心 + 实验耐心 + 喜欢观察自然现象",
  },
  {
    id: "sci-math",
    zh: "数学 / 统计",
    category: "调研型",
    hollandCode: "ICA",
    bigFiveFit: { C: "high" },
    cognitiveFit: { Gf: "high" },
    majors: [
      { name: "数学与应用数学", code: "070101" },
      { name: "信息与计算科学", code: "070102" },
      { name: "统计学",         code: "071201" },
    ],
    subjectsRequired: ["物理"],
    description: "纯数 + 应用数学 + 统计;基础理论或转金融/AI 都常见",
    fitNotes: "极高流体推理 + 能在抽象中长时间专注",
  },

  // ─── 经管金融型 ───────────────────────────────────────
  {
    id: "biz-finance",
    zh: "金融 / 经济",
    category: "经管金融型",
    hollandCode: "ECI",
    bigFiveFit: { C: "high", E: "high" },
    cognitiveFit: { Gf: "high" },
    majors: [
      { name: "金融学",         code: "020301K" },
      { name: "经济学",         code: "020101" },
      { name: "投资学",         code: "020304" },
      { name: "金融工程",       code: "020302" },
    ],
    subjectsRequired: ["物理"],
    subjectsRecommended: ["化学"],
    description: "金融市场、投资、经济分析;就业薪资高、压力大",
    fitNotes: "高企业型 + 高数学/逻辑 + 风险耐受",
  },
  {
    id: "biz-management",
    zh: "工商管理 / 人力",
    category: "经管金融型",
    hollandCode: "ESC",
    bigFiveFit: { E: "high", C: "high" },
    majors: [
      { name: "工商管理",       code: "120201K" },
      { name: "人力资源管理",   code: "120206" },
      { name: "市场营销",       code: "120202" },
      { name: "财务管理",       code: "120204" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["物理"],
    description: "企业管理、人力、营销、财务;选科限制少",
    fitNotes: "高外向 + 沟通能力 + 组织协调",
  },
  {
    id: "biz-accounting",
    zh: "会计 / 审计",
    category: "经管金融型",
    hollandCode: "CEI",
    bigFiveFit: { C: "high" },
    majors: [
      { name: "会计学",   code: "120203K" },
      { name: "审计学",   code: "120207" },
      { name: "税收学",   code: "020202" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["物理"],
    description: "财务记录、审计、税务;就业稳定、可考证(CPA)",
    fitNotes: "极高 C 常规型(细致、有条理) + 抗重复",
  },

  // ─── 社会 / 教育 / 法律 ────────────────────────────────
  {
    id: "soc-law",
    zh: "法学",
    category: "社会服务型",
    hollandCode: "EIS",
    bigFiveFit: { C: "high", E: "high" },
    cognitiveFit: { Gc: "high" },
    majors: [
      { name: "法学",         code: "030101K" },
      { name: "知识产权",     code: "030102T" },
      { name: "国际经济与贸易法", code: "030104T" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["历史", "政治"],
    description: "立法、司法、律师、法务;长期学习 + 司考门槛",
    fitNotes: "极强语言表达 + 逻辑推理 + 高责任感",
  },
  {
    id: "soc-edu",
    zh: "教育 / 师范",
    category: "社会服务型",
    hollandCode: "SIA",
    bigFiveFit: { A: "high", C: "high" },
    majors: [
      { name: "教育学",       code: "040101" },
      { name: "学前教育",     code: "040106" },
      { name: "小学教育",     code: "040107" },
      { name: "数学/物理/化学/生物 教育", code: "070101 系列" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["历史"],
    description: "教学、教研、教育管理;就业稳定、有寒暑假",
    fitNotes: "高 S 社会型 + 同情心 + 耐心",
  },
  {
    id: "soc-psych",
    zh: "心理学",
    category: "社会服务型",
    hollandCode: "ISA",
    bigFiveFit: { O: "high", A: "high" },
    cognitiveFit: { Gc: "high" },
    majors: [
      { name: "心理学",       code: "071101" },
      { name: "应用心理学",   code: "071102" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["生物"],
    description: "心理咨询、心理学研究、人因工程",
    fitNotes: "高同情心 + 高开放性 + 善于自我反思",
  },
  {
    id: "soc-public",
    zh: "公共管理 / 行政",
    category: "社会服务型",
    hollandCode: "ESC",
    bigFiveFit: { C: "high" },
    majors: [
      { name: "行政管理",     code: "120402" },
      { name: "公共事业管理", code: "120401" },
      { name: "城市管理",     code: "120405T" },
    ],
    subjectsRequired: [],
    description: "政府、事业单位、公共事务;考公主流路径",
    fitNotes: "组织性 + 责任感 + 能与多元利益方协作",
  },

  // ─── 艺术 / 创意 ──────────────────────────────────────
  {
    id: "art-design",
    zh: "设计学",
    category: "艺术创意型",
    hollandCode: "AIE",
    bigFiveFit: { O: "high" },
    cognitiveFit: { Gv: "high" },
    majors: [
      { name: "视觉传达设计", code: "130502" },
      { name: "环境设计",     code: "130503" },
      { name: "产品设计",     code: "130504" },
      { name: "服装与服饰设计", code: "130505" },
      { name: "数字媒体艺术", code: "130508" },
    ],
    subjectsRequired: [],
    description: "平面 / 工业 / 数字媒体设计;艺考路径或综合录取",
    fitNotes: "高开放性 + 视觉空间 + 高 A 艺术型",
  },
  {
    id: "art-arts",
    zh: "美术 / 美院",
    category: "艺术创意型",
    hollandCode: "AIE",
    bigFiveFit: { O: "high" },
    majors: [
      { name: "美术学",   code: "130401" },
      { name: "绘画",     code: "130402" },
      { name: "雕塑",     code: "130403" },
      { name: "中国画",   code: "130406T" },
    ],
    subjectsRequired: [],
    description: "纯艺术创作 / 美术学;艺考为主",
    fitNotes: "极高 A + 长期实践积累 + 强自我表达",
  },
  {
    id: "art-media",
    zh: "新闻 / 传媒",
    category: "艺术创意型",
    hollandCode: "AES",
    bigFiveFit: { O: "high", E: "high" },
    cognitiveFit: { Gc: "high" },
    majors: [
      { name: "新闻学",       code: "050301" },
      { name: "广播电视学",   code: "050302" },
      { name: "广告学",       code: "050303" },
      { name: "网络与新媒体", code: "050306T" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["历史"],
    description: "新闻采编、广告、新媒体;行业转型剧烈",
    fitNotes: "强语言 + 沟通能力 + 高开放性",
  },

  // ─── 文史哲 ─────────────────────────────────────────
  {
    id: "hum-chinese",
    zh: "汉语言文学",
    category: "人文型",
    hollandCode: "AIS",
    bigFiveFit: { O: "high" },
    cognitiveFit: { Gc: "high" },
    majors: [
      { name: "汉语言文学",   code: "050101" },
      { name: "汉语国际教育", code: "050103" },
      { name: "古典文献学",   code: "050104" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["历史"],
    description: "文学研究、写作编辑、对外汉语",
    fitNotes: "极高语言能力 + 阅读耐力 + 文化敏感",
  },
  {
    id: "hum-foreign",
    zh: "外语 / 翻译",
    category: "人文型",
    hollandCode: "ASI",
    bigFiveFit: { O: "high", C: "high" },
    cognitiveFit: { Gc: "high" },
    majors: [
      { name: "英语",     code: "050201" },
      { name: "翻译",     code: "050261" },
      { name: "日语 / 法语 / 德语 / 西班牙语", code: "050207-050217" },
    ],
    subjectsRequired: [],
    description: "外语教学、翻译、外贸、外交;路径多元",
    fitNotes: "强语言 + 跨文化兴趣 + 持续记忆/练习耐力",
  },
  {
    id: "hum-history",
    zh: "历史 / 考古",
    category: "人文型",
    hollandCode: "IAS",
    bigFiveFit: { O: "high" },
    cognitiveFit: { Gc: "high" },
    majors: [
      { name: "历史学",     code: "060101" },
      { name: "考古学",     code: "060103" },
      { name: "文物与博物馆学", code: "060104" },
    ],
    subjectsRequired: ["历史"],
    description: "历史研究、考古、博物馆;多走研究路径",
    fitNotes: "对过去高度好奇 + 长篇阅读耐力 + 严谨求证",
  },
  {
    id: "hum-philos",
    zh: "哲学",
    category: "人文型",
    hollandCode: "IAS",
    bigFiveFit: { O: "high" },
    cognitiveFit: { Gf: "high", Gc: "high" },
    majors: [
      { name: "哲学",         code: "010101" },
      { name: "逻辑学",       code: "010102" },
      { name: "宗教学",       code: "010103K" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["历史", "政治"],
    description: "哲学思考、伦理研究;多读研、社科或法学跨界",
    fitNotes: "极高开放性 + 流体推理 + 享受抽象问题",
  },

  // ─── 农学 / 食品 / 环境 ────────────────────────────────
  {
    id: "agri-bio",
    zh: "农学 / 食品",
    category: "农林型",
    hollandCode: "RIA",
    bigFiveFit: { C: "high" },
    majors: [
      { name: "园艺",         code: "090102" },
      { name: "食品科学与工程", code: "082701" },
      { name: "农学",         code: "090101" },
      { name: "动物医学",     code: "090401" },
    ],
    subjectsRequired: ["化学", "生物"],
    description: "现代农业、食品科技、动物医学;政策支持持续",
    fitNotes: "对自然有兴趣 + 实验耐心 + 户外耐受",
  },
  {
    id: "env-eco",
    zh: "环境 / 生态",
    category: "调研型",
    hollandCode: "IRA",
    bigFiveFit: { O: "high", C: "high" },
    majors: [
      { name: "环境科学",     code: "082503" },
      { name: "环境工程",     code: "082502" },
      { name: "生态学",       code: "071004" },
    ],
    subjectsRequired: ["化学"],
    subjectsRecommended: ["物理", "生物"],
    description: "环境保护、生态恢复、双碳;政策驱动",
    fitNotes: "对自然系统好奇 + 跨学科整合 + 长期主义",
  },

  // ─── 服务 / 体育 ──────────────────────────────────────
  {
    id: "ser-tourism",
    zh: "旅游 / 酒店",
    category: "服务型",
    hollandCode: "ESC",
    bigFiveFit: { E: "high", A: "high" },
    majors: [
      { name: "旅游管理", code: "120901K" },
      { name: "酒店管理", code: "120902" },
      { name: "会展经济与管理", code: "120903" },
    ],
    subjectsRequired: [],
    description: "旅游、酒店、会展、文旅;强人际、流动性大",
    fitNotes: "高 S+E + 跨文化沟通 + 高情绪稳定",
  },
  {
    id: "ser-sports",
    zh: "体育 / 运动",
    category: "服务型",
    hollandCode: "RES",
    bigFiveFit: { E: "high" },
    majors: [
      { name: "体育教育",     code: "040201" },
      { name: "运动训练",     code: "040202K" },
      { name: "运动康复",     code: "040206T" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["生物"],
    description: "体育教学、运动训练、康复;往往需体育专项",
    fitNotes: "高活力 + 身体能力 + 抗压",
  },

  // ─── 军警 / 公安 ─────────────────────────────────────
  {
    id: "mil-police",
    zh: "公安 / 军事",
    category: "执法型",
    hollandCode: "REC",
    bigFiveFit: { C: "high", E: "high" },
    majors: [
      { name: "侦查学",       code: "030605TK" },
      { name: "治安学",       code: "030601K" },
      { name: "国防教育",     code: "040108T" },
    ],
    subjectsRequired: [],
    subjectsRecommended: ["物理"],
    description: "公安院校 / 军校;特殊招录、政治审查",
    fitNotes: "极高责任感 + 抗压 + 体能要求",
  },
];
